# Generated by Django 4.0.3 on 2022-05-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mofast',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
