# Generated by Django 4.0.3 on 2022-05-13 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_mofast_percentage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mofast',
            options={'verbose_name_plural': 'Mofast'},
        ),
        migrations.CreateModel(
            name='WarehouseKe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total', models.IntegerField()),
                ('scheduled', models.IntegerField()),
                ('cancelled', models.IntegerField()),
                ('pending', models.IntegerField()),
                ('percentage', models.FloatField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ke-Warehouse',
            },
        ),
        migrations.CreateModel(
            name='Vital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total', models.IntegerField()),
                ('scheduled', models.IntegerField()),
                ('cancelled', models.IntegerField()),
                ('pending', models.IntegerField()),
                ('percentage', models.FloatField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vital',
            },
        ),
        migrations.CreateModel(
            name='Unateus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total', models.IntegerField()),
                ('scheduled', models.IntegerField()),
                ('cancelled', models.IntegerField()),
                ('pending', models.IntegerField()),
                ('percentage', models.FloatField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Unateus',
            },
        ),
        migrations.CreateModel(
            name='Trade2w',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total', models.IntegerField()),
                ('scheduled', models.IntegerField()),
                ('cancelled', models.IntegerField()),
                ('pending', models.IntegerField()),
                ('percentage', models.FloatField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '2W Trade',
            },
        ),
        migrations.CreateModel(
            name='Mainstream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total', models.IntegerField()),
                ('scheduled', models.IntegerField()),
                ('cancelled', models.IntegerField()),
                ('pending', models.IntegerField()),
                ('percentage', models.FloatField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mainstream',
            },
        ),
        migrations.CreateModel(
            name='Halisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total', models.IntegerField()),
                ('scheduled', models.IntegerField()),
                ('cancelled', models.IntegerField()),
                ('pending', models.IntegerField()),
                ('percentage', models.FloatField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Halisi',
            },
        ),
        migrations.CreateModel(
            name='Eglobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total', models.IntegerField()),
                ('scheduled', models.IntegerField()),
                ('cancelled', models.IntegerField()),
                ('pending', models.IntegerField()),
                ('percentage', models.FloatField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Eglobal',
            },
        ),
        migrations.CreateModel(
            name='Clinton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total', models.IntegerField()),
                ('scheduled', models.IntegerField()),
                ('cancelled', models.IntegerField()),
                ('pending', models.IntegerField()),
                ('percentage', models.FloatField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clinton Stores',
            },
        ),
        migrations.CreateModel(
            name='BNE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total', models.IntegerField()),
                ('scheduled', models.IntegerField()),
                ('cancelled', models.IntegerField()),
                ('pending', models.IntegerField()),
                ('percentage', models.FloatField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '2BNE',
            },
        ),
        migrations.CreateModel(
            name='Adlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total', models.IntegerField()),
                ('scheduled', models.IntegerField()),
                ('cancelled', models.IntegerField()),
                ('pending', models.IntegerField()),
                ('percentage', models.FloatField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Adlat',
            },
        ),
    ]
