# Generated by Django 4.0.3 on 2022-05-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
